Adjusted deep case image size & added staff members
LIFSHallym/LIFSResearchBlog pull request #90
Opened 2023-01-27 02:10 UTC by supportpark

1. 딥케이스 이미지 사이즈 수정
2. _config.yml - staff 주석풀었음
3. people.yml - staff member 추가(시원 서희 명훈)
4. staff 이미지 파일 추가

2023-01-27 11:48 UTC, outspark commented
@supportpark haksa.jpg 이미지(프로필 아이콘) 교환. 이미지 명칭 방법 통일.

2023-01-27 11:53 UTC, outspark requested changes
1. 학사 이미지 -> 프로필 아이콘을 변경.
2. staff  bio 내용 변경. Admin/Undergrad...
3. 파일 추가할 때 다른 파일명 작성법에 따라 작성. 현재 영어로 작성 중.

2023-01-30 07:59 UTC, supportpark commented
1. 프로필 아이콘 변경완료
2. 수정완료 (Administrator / Undergraduate으로 수정완료
3. 확인완료했습니닷

2023-01-31 01:54 UTC, outspark approved these changes

2023-01-31 01:54 UTC, merged